# Generated by Django 3.1.7 on 2023-07-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default="Django Club's Blog", max_length=255),
        ),
    ]
