# Generated by Django 3.1.7 on 2023-07-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0002_post_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_tag',
            field=models.CharField(default='Django', max_length=255),
        ),
    ]
