# Generated by Django 3.1.7 on 2023-07-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_auto_20230725_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Blog Post ...', max_length=1000),
        ),
    ]
