# Generated by Django 3.1.7 on 2023-07-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0009_auto_20230726_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
