# Generated by Django 3.1.7 on 2023-07-28 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0015_auto_20230727_1629'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
