# Generated by Django 3.2.2 on 2023-08-12 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0016_delete_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-post_date']},
        ),
    ]
