# Generated by Django 3.2.20 on 2023-07-29 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblogfa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postfa',
            old_name='category',
            new_name='categoryfa',
        ),
    ]
