# Generated by Django 3.2.20 on 2023-07-29 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblogfa', '0002_rename_category_postfa_categoryfa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postfa',
            old_name='categoryfa',
            new_name='category',
        ),
    ]
