# Generated by Django 3.2.2 on 2023-08-12 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblogfa', '0003_rename_categoryfa_postfa_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postfa',
            options={'ordering': ['-post_date']},
        ),
    ]
