# Generated by Django 3.2.2 on 2023-08-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationResultsKNearest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature', models.FloatField()),
                ('L', models.FloatField()),
                ('R', models.FloatField()),
                ('A_M', models.FloatField()),
                ('Color', models.FloatField()),
                ('Spectral_Class', models.FloatField()),
                ('Type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationResultsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pregnancies', models.FloatField()),
                ('Glucose', models.FloatField()),
                ('BloodPressure', models.FloatField()),
                ('SkinThickness', models.FloatField()),
                ('Insulin', models.FloatField()),
                ('BMI', models.FloatField()),
                ('DiabetesPedigreeFunction', models.FloatField()),
                ('Age', models.FloatField()),
                ('classification', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationResultsNB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.FloatField()),
                ('Sex', models.FloatField()),
                ('BP', models.FloatField()),
                ('Cholesterol', models.FloatField()),
                ('Na_to_K', models.FloatField()),
                ('Drug', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationResultsSVM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.FloatField()),
                ('sepal_width', models.FloatField()),
                ('petal_length', models.FloatField()),
                ('petal_width', models.FloatField()),
                ('classification', models.CharField(max_length=30)),
            ],
        ),
    ]
