# Generated by Django 3.2.2 on 2023-08-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationResultsRF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RI', models.FloatField()),
                ('Na', models.FloatField()),
                ('Mg', models.FloatField()),
                ('Al', models.FloatField()),
                ('Si', models.FloatField()),
                ('K', models.FloatField()),
                ('Ca', models.FloatField()),
                ('Ba', models.FloatField()),
                ('Fe', models.FloatField()),
                ('Type', models.CharField(max_length=30)),
            ],
        ),
    ]
