# Generated by Django 3.2.2 on 2023-08-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_classificationresultsrf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationResultsDT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weight', models.FloatField()),
                ('Length1', models.FloatField()),
                ('Length2', models.FloatField()),
                ('Length3', models.FloatField()),
                ('Height', models.FloatField()),
                ('Width', models.FloatField()),
                ('Species', models.CharField(max_length=30)),
            ],
        ),
    ]
