# Generated by Django 3.2.2 on 2023-08-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0003_classificationresultsdt'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegressionResultsLinear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SqFt', models.FloatField()),
                ('Bedrooms', models.FloatField()),
                ('Bathrooms', models.FloatField()),
                ('Offers', models.FloatField()),
                ('Brick', models.FloatField()),
                ('Neighborhood', models.FloatField()),
                ('Price', models.FloatField()),
            ],
        ),
    ]
