# Generated by Django 3.2.2 on 2023-08-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0004_regressionresultslinear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationresultsrf',
            name='Type',
            field=models.CharField(max_length=60),
        ),
    ]
