# Generated by Django 3.2.2 on 2023-08-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0005_alter_classificationresultsrf_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegressionResultsPolynomial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_acidity', models.FloatField()),
                ('volatile_acidity', models.FloatField()),
                ('citric_acid', models.FloatField()),
                ('residual_sugar', models.FloatField()),
                ('chlorides', models.FloatField()),
                ('free_sulfur_dioxide', models.FloatField()),
                ('total_sulfur_dioxide', models.FloatField()),
                ('density', models.FloatField()),
                ('pH', models.FloatField()),
                ('sulphates', models.FloatField()),
                ('alcohol', models.FloatField()),
                ('quality', models.FloatField()),
            ],
        ),
    ]
