# Generated by Django 3.2.2 on 2023-08-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0006_regressionresultspolynomial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegressionResultsLasso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carat', models.FloatField()),
                ('cut', models.FloatField()),
                ('color', models.FloatField()),
                ('clarity', models.FloatField()),
                ('depth', models.FloatField()),
                ('table', models.FloatField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
