# Generated by Django 3.2.2 on 2023-08-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0007_regressionresultslasso'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegressionResultsRidge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('depth', models.FloatField()),
                ('magnitude', models.FloatField()),
            ],
        ),
    ]
