# Generated by Django 3.2.2 on 2023-08-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0008_regressionresultsridge'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegressionResultsElasticNet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.FloatField()),
                ('Job', models.FloatField()),
                ('Salary', models.FloatField()),
            ],
        ),
    ]
